name: grapheme_splitter
version: 1.0.0
author: Javier Lecuona <javierlecuona@gmail.com>
description: A Dart library that breaks strings into their individual user-perceived characters.
homepage: https://github.com/javiercbk/grapheme_splitter
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:

dev_dependencies:
  test: ^1.17.10
  path: ^1.8.0
  pedantic: ^1.11.0
