name: json2class
version: 1.0.0
description: A library that generates Dart / Typescript classes (parse and generator included) from a json string.
environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none

dependencies:
  json_ast:
    path: packages/json_ast

  convert: ^3.0.1
  dart_style: ^2.0.2
  collection: ^1.15.0-nullsafety.4
  js: ^0.6.3

dev_dependencies:
  pedantic: ^1.11.1
